# Generated by Django 3.0.1 on 2020-01-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'positive'), ('neutral', 'neutral'), ('negative', 'negative')], max_length=10, null=True),
        ),
    ]
