# Generated by Django 3.0.1 on 2020-01-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sentiment',
        ),
    ]
